site_name: 'How to gas up the snowblower'
site_description: 'A single page guide to filling the snowblower with one MicroSim for calculating the oil'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/how-to-gas-up-the-snowblower/'
repo_url: 'https://github.com/dmccreary/how-to-gas-up-the-snowblower'
edit_uri: 'blob/master/docs'


nav:
  - Home: index.md
  - MicroSims:
    - Gas and Oil Mix Calculator: sims/gas-oil-mix/index.md

theme:
  name: material