site_name: 'Claude Skills for Intelligent Textbooks'
site_description: 'A collection of skills and techniques for building intelligent textbooks using Claude AI.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/claude-skills/'
repo_url: 'https://github.com/dmccreary/claude-skills'
edit_uri: 'blob/master/docs'


nav:
  - Home: index.md
  - MicroSims:
    - Gas and Oil Mix Calculator: sims/gas-oil-mix/index.md

theme:
  name: material